version: 2

models:
  - name: dim_trip_data_aug_filtered
    description: The distance for trip in August
    columns:
      - name: trip_distance
        description: Number of distance
        tests:
          - not_null
      - name: store_and_fwd_flag
        description: Store and Forward Trip
        test:
          - accepted_values:
            values: ['Y', 'N']